### ISSUE TITLE
“detours/detours.h”: No such file or directory

### ISSUE THREAD

**Issue by kidgokugoku** [Z4ee/Pipsi-SR#1]
“detours/detours.h”: No such file or directory

error occurred when building `Cheat`.

**Comment by Z4ee** [comment]
```
git clone https://github.com/microsoft/vcpkg
cd vcpkg
bootstrap-vcpkg.bat
vcpkg integrate install
vcpkg install detours:x64-windows-static-release
```

then

![image](https://github.com/Z4ee/Pipsi-SR/assets/113752393/15431f3f-5687-4cad-ab3f-9eb56e21d9c4)

**Comment by kidgokugoku** [comment]
> ```
> git clone https://github.com/microsoft/vcpkg
> cd vcpkg
> bootstrap-vcpkg.bat
> vcpkg integrate install
> vcpkg install detours:x64-windows-static-release
> ```
> 
> then
> 
> ![image](https://private-user-images.githubusercontent.com/113752393/303839063-15431f3f-5687-4cad-ab3f-9eb56e21d9c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzIzNDcsIm5iZiI6MTcwNzU3MjA0NywicGF0aCI6Ii8xMTM3NTIzOTMvMzAzODM5MDYzLTE1NDMxZjNmLTU2ODctNGNhZC1hYjNmLTllYjU2ZTIxZDljNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxMzM0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTU0MzZlOWViMWExZTE4NGYxZGYwZTRhZDgyNGFiMTlmNTZjZTRmMTc2ZmM1OTAyYWRhNGMxMDMxMmI1YWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qb5I7mJSv7L7E99_egiB5AC0YGFaPbnJy8Dh3cO5HUA)

thanks, it works perfectly.
btw, would you consider supporting China version?

**Comment by Z4ee** [comment]
> Btw, would you consider supporting China version?

I will add support for Chinese version of the game after I make `auto-talk` and `esp`.
