### ISSUE TITLE
battle speed hack trigger 2010 error 

### ISSUE THREAD

**Issue by kidgokugoku** [Z4ee/Pipsi-SR#10]
battle speed hack sometimes trigger 2010 error, usually after fighting open world enemies. ( my observation, not really sure, i tried adding 1s delay after entering a battle, but it didn't work )

And fighting certain enemy types with speedhack have a high possibility freezing the game ( after enemy turn ), happened to me multiple times, I'm pretty sure it's a bug in game.

**Comment by Z4ee** [comment]
> battle speed hack sometimes trigger 2010 error, usually after fighting open world enemies. ( my observation, not really sure, i tried adding 1s delay after entering a battle, but it didn't work )
try this: https://github.com/Z4ee/Pipsi-SR/releases/tag/0.4.1

if error №2010 persists, then send logs from the console here

> And fighting certain enemy types with speedhack have a high possibility freezing the game ( after enemy turn ), happened to me multiple times, I'm pretty sure it's a bug in game.

I've never had a freeze in battle

**Comment by kidgokugoku** [comment]
![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/4d258b43-f6c0-4fd4-bf31-e187512226b1)

i tried the same battle 4 times, the last time used 1 less round and it didn't get the error
```
Statistics->totalDelayCumulate: 24.000000
Statistics->costTime: 13.791233
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Noclip::Update(), exception 0xC0000005
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Esp::Update(), exception 0xC0000005
Esp::Update(), exception 0xC0000005
Statistics->totalDelayCumulate: 23.000000
Statistics->costTime: 13.830441
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Noclip::Update(), exception 0xC0000005
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Esp::Update(), exception 0xC0000005
Esp::Update(), exception 0xC0000005
Esp::Update(), exception 0xC0000005
Statistics->totalDelayCumulate: 24.000000
Statistics->costTime: 14.950929
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Noclip::Update(), exception 0xC0000005
ShareBuff Size Almost Use UP 80%!!! pos:1, size:1
Esp::Update(), exception 0xC0000005
Esp::Update(), exception 0xC0000005
Statistics->totalDelayCumulate: 16.000000
Statistics->costTime: 13.961764
```

**Comment by kidgokugoku** [comment]
> hmm
> 
> try this: [Release.zip](https://github.com/Z4ee/Pipsi-SR/files/14278105/Release.zip)

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/269022c0-cc9e-424a-adad-54ead8eb8b88)

5x or slower works fine though. And current version of speed hacking is not skipping ult animation and some other animation anyway, so maybe leave it this way.

p.s. your new patch crashes my game...

**Comment by kidgokugoku** [comment]
> hmm
> 
> try this: [Release.zip](https://github.com/Z4ee/Pipsi-SR/files/14278105/Release.zip)

It's easy to reproduce the bug in Hyperlink Matches mission.

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/ae14da40-2628-4c71-8690-ffa471f7b864)

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/d1d87383-1109-4c6a-88b4-e0d214b6a583)

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/0c94349c-c001-442a-b33a-907766b132ad)

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/483a00e2-83a6-4aea-8d93-dbd5df1f78ed)

![图片](https://github.com/Z4ee/Pipsi-SR/assets/82298915/beafebe7-68c0-44ee-9af6-cfbdcb4456bc)

all these results are from the same battle.

**Comment by Z4ee** [comment]
their system looks like this

```
if (StartBattleReqTime + TotalSkillPerformTime > EndBattleReqTime)
	printf("speedhack detected\n");
```

and since this all happens on the server, I can’t do anything

**Comment by Z4ee** [comment]
try this: https://github.com/Z4ee/Pipsi-SR/releases/tag/0.5

**Comment by kidgokugoku** [comment]
> their system looks like this
> 
> ```
> if (StartBattleReqTime + TotalSkillPerformTime > EndBattleReqTime)
> 	printf("speedhack detected\n");
> ```
> 
> and since this all happens on the server, I can’t do anything


> try this: https://github.com/Z4ee/Pipsi-SR/releases/tag/0.5

well it works fine now, thanks!
it's pretty clever to only speed up enemies' turn.
