### ISSUE TITLE
Launcher throws error executing on windows

### ISSUE THREAD

**Issue by Elfi3s** [Z4ee/Pipsi-SR#13]
Open launcher and this happens

![image](https://github.com/Z4ee/Pipsi-SR/assets/153373877/ba859044-66f9-48b2-815a-5209fdc8c71f)

**Comment by Z4ee** [comment]
Do you have Windows Defender enabled?

**Comment by Elfi3s** [comment]
its ok solved it by compiling the launcher myself. strange tho.
