### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Rads-D** [Z4ee/Pipsi-SR#2]
![Screenshot 2024-02-10 225541](https://github.com/Z4ee/Pipsi-SR/assets/153896527/cfcab0e2-f8e6-498d-9bfb-5cfc6ccec541)
![Screenshot 2024-02-10 225506](https://github.com/Z4ee/Pipsi-SR/assets/153896527/b7d74b01-fc5d-4539-b7cd-2e43d8530df9)

**Comment by Rads-D** [comment]
I've also used this method
=================
git clone https://github.com/microsoft/vcpkg
cd vcpkg
bootstrap-vcpkg.bat
vcpkg integrate install
vcpkg install detours:x64-windows-static-release

**Comment by kidgokugoku** [comment]
> # I've also used this method
> 
> git clone https://github.com/microsoft/vcpkg cd vcpkg bootstrap-vcpkg.bat vcpkg integrate install vcpkg install detours:x64-windows-static-release

I think you need to change `Use Static Libraries` to `Yes`

if it don't work, you can try:

copying `detours.h` and `detours.lib` to Cheat directory, then modified hook.cpp
```cpp
#include "detours.h"
#pragma comment (lib,"detours.lib")
```

**Comment by Z4ee** [comment]
> # I've also used this method
> git clone https://github.com/microsoft/vcpkg cd vcpkg bootstrap-vcpkg.bat vcpkg integrate install vcpkg install detours:x64-windows-static-release

![image](https://github.com/Z4ee/Pipsi-SR/assets/113752393/980efdb5-81fd-4fc5-b798-89e02b04c588)

**Comment by Rads-D** [comment]
![image](https://github.com/Z4ee/Pipsi-SR/assets/153896527/dc3bdacc-6a19-4a6c-a1e7-0b2e86846841)
thanks this is very helpful
