### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by zaleyatax** [Z4ee/Pipsi-SR#3]
![image](https://github.com/Z4ee/Pipsi-SR/assets/113115683/027e5ab2-ab30-4bb7-8c88-664e1ac132aa)
![image](https://github.com/Z4ee/Pipsi-SR/assets/113115683/a9639173-cda6-4f7b-9bfc-d0010f9e5dee)
how can i fix this

**Comment by zaleyatax** [comment]
i fixed this issue but it now gives me this error
![image](https://github.com/Z4ee/Pipsi-SR/assets/113115683/2cb41eeb-6e15-4872-8120-3f1c9c62b5c2)

**Comment by Z4ee** [comment]
try this: https://github.com/Z4ee/Pipsi-SR/commit/8026a9b08948a4b570afff428a87406937c0e748
and show your injection logs
and show C:\Windows\Pipsi-SR.ini

**Comment by zaleyatax** [comment]
thank you it works
