### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by stretcher98** [Z4ee/Pipsi-SR#4]
![image](https://github.com/Z4ee/Pipsi-SR/assets/159675139/572bee54-bf82-45ca-8e1b-7c8107d32ad2)
How do i fix this?, and can i use the epic game launcher version of honkai star rail for this.

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-SR/issues/2
https://github.com/Z4ee/Pipsi-SR/issues/1

**Comment by stretcher98** [comment]
and can i use the epic game launcher version of honkai star rail for this.

**Comment by Z4ee** [comment]
> and can i use the epic game launcher version of honkai star rail for this.

probably yes

**Comment by stretcher98** [comment]
Btw thanks for the help <3
