### ISSUE TITLE
Cannot open include file: 'detours.h' (even though you have followed all the methods)

### ISSUE THREAD

**Issue by ketiketi77** [Z4ee/Pipsi-SR#6]
![adasdasda](https://github.com/Z4ee/Pipsi-SR/assets/159681881/1db3215d-d29d-47bd-987a-6d286d0c4424)

I have installed vcpkg and set use static libraries to yes but still like this

**Comment by Z4ee** [comment]
`vcpkg install detours:x64-windows-static`?

**Comment by ketiketi77** [comment]
![image](https://github.com/Z4ee/Pipsi-SR/assets/159681881/201499c1-27ec-4b98-bb03-98899eed16b9)
thanks brooo

**Comment by ketiketi77** [comment]
![ty](https://github.com/Z4ee/Pipsi-SR/assets/159681881/0d09d5c0-596f-43fd-a053-0fef92098727)
thanks brooo
