### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Shin13bzx** [Z4ee/Pipsi-SR#7]
Hi can you tell me how to Сompile the solution :D?

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-SR/releases/tag/0.1

**Comment by Shin13bzx** [comment]
thanks you very much! have a good day sir

**Comment by Z4ee** [comment]
can you give me your discord

**Comment by Shin13bzx** [comment]
Sh1n#4972
