### ISSUE TITLE
Is it possible to dump global-metadata using this tool?

### ISSUE THREAD

**Issue by VicoErv** [Z4ee/Pipsi-SR#8]

**Comment by Z4ee** [comment]
It just cheat, not a dumper

**Comment by VicoErv** [comment]
So you get the offsets without dumping it?

**Comment by Z4ee** [comment]
I wrote a dumper, then dumped the game

then I wrote a cheat and posted it on github

**Comment by VicoErv** [comment]
can you tell me first and last 8 byte of the decrypted metadata

**Comment by Z4ee** [comment]
> can you tell me first and last 8 byte of the decrypted metadata

I'm sorry, I can't tell you
