### ISSUE TITLE
quest tp , chest tp and no clip not working

### ISSUE THREAD

**Issue by JesserTN** [Z4ee/Pipsi-SR#9]
![image](https://github.com/Z4ee/Pipsi-SR/assets/107747414/1843b339-f2cb-4895-a98a-ed2c673dc669)

**Comment by Z4ee** [comment]
check is fov changer working?

**Comment by Z4ee** [comment]
if it doesn’t work either, it means that the cheat couldn’t hook the required function

then just try restarting

**Comment by JesserTN** [comment]
fov changer also not working 
also i noticed when i press the key i assigned for chest teleport the character just move forward like if no clip was enabled

**Comment by Z4ee** [comment]
Looks like the cheat was unable to hook the functions

just try restarting the cheat

> fov changer also not working also i noticed when i press the key i assigned for chest teleport the character just move forward like if no clip was enabled

**Comment by Z4ee** [comment]
> > if it doesn’t work either, it means that the cheat couldn’t hook the required function
> > then just try restarting
> > i restarted after the game froze while in loading screen

try again

**Comment by JesserTN** [comment]
all 3 works now ! thanks 
![Uploading image.png…]()
also when restarting the cheat the key binds reset

**Comment by Z4ee** [comment]
> also when restarting the cheat the key binds reset

this is because there is no saving of settings yet
